name: Lint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test